version: "3.9"
services:
  comdb2:
    #    container_name: comdb2db 
    hostname: comdb2db
    image: bloomberg/comdb2-dev:latest
    working_dir: /home/heisengarg
    command: default 
    volumes:
      - comdb2-opt-bb:/opt/bb/
      - comdb2-dbs:/home/heisengarg/dbs
    expose: [5105]
    cap_add:
      - ALL
    stdin_open: true # docker run -i
    tty: true

# docker compose prepends the project name
# while creating a volume, but since we are
# trying to use a volume populated by external
# install in a separate container, we want to
# use that volume and not let docker-compose
# manage one for us
volumes:
  comdb2-opt-bb:
    external:
      name: comdb2-opt-bb
  comdb2-dbs:
    external:
      name: comdb2-dbs
